app_name: cartflow  # Elastic Beanstalk application name
environment_name: cartflow-stag  # Elastic Beanstalk environment name
ecr_repo_name: cartflow  # ECR repository name
region: us-east-1  # AWS region
